name: ci

on:
  push:
    branches:
      - "**"
  pull_request:

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller webrtcvad-wheels

      - name: Build one-file Windows exe
        run: |
          pyinstaller --noconfirm --clean --onefile --windowed --name VoiceDict --additional-hooks-dir hooks voice_dict.py

      - name: Package artifact (zip)
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path releases | Out-Null
          $name = "VoiceDict-Windows-x64-${{ github.sha }}.zip"
          Compress-Archive -Path dist/VoiceDict.exe -DestinationPath ("releases/" + $name) -Force
          echo "ARTIFACT_NAME=$name" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: VoiceDict-Windows-x64
          path: releases/${{ env.ARTIFACT_NAME }}
